services:
  producer:
    image: producer
    container_name: producer
    pull_policy: build
    build:
      context: .
      dockerfile: ./Dockerfile-producer
    depends_on:
      - redpanda-0
    networks:
      - wiki
  consumer:
    image: consumer
    container_name: consumer
    pull_policy: build
    build:
      context: .
      dockerfile: ./Dockerfile-consumer
    ports:
      - "80:80"
    depends_on:
      redpanda-0:
        condition: service_started
      database-init:
        condition: service_completed_successfully
    networks:
      - wiki

  redpanda-0:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda-0:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda-0:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda-0:33145
      - --advertise-rpc-addr redpanda-0:33145
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.2
    container_name: redpanda-0
    volumes:
      - redpanda-0:/var/lib/redpanda/data
    networks:
      - wiki
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644

  console:
    container_name: redpanda-console
    image: docker.redpanda.com/redpandadata/console:v2.7.0
    networks:
      - wiki
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda-0:9092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda-0:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda-0:9644"]
    ports:
      - 8080:8080
    depends_on:
      - redpanda-0

  database:
    image: cassandra:latest
    container_name: database
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=database
    healthcheck:
        test: ["CMD-SHELL", "nodetool status"]
        interval: 30s
        timeout: 10s
        retries: 5
    volumes:
      - ./database-data:/var/lib/cassandra
    networks:
      - wiki

  database-init:
    image: cassandra:latest
    depends_on:
      database:
        condition: service_healthy
    restart: "no"
    entrypoint: ["/init.sh", "database"]
    volumes:
      - ./data/scripts/init.sh:/init.sh
    networks:
      - wiki

volumes:
  redpanda-0: null

networks:
  wiki:
    driver: bridge
