# Build stage
FROM golang:1.25.1 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY cmd ./cmd
COPY configuration ./configuration
COPY data ./data
COPY models ./models
COPY server ./server
COPY utils ./utils
COPY wiki ./wiki

ENV CGO_ENABLED=0
ENV GOOS=linux

RUN go build -o bin/producer ./cmd/producer/main.go

# Runtime stage
FROM gcr.io/distroless/base

COPY --from=builder /app/bin/producer /producer
COPY wiki_updates.conf.json /wiki_updates.conf.json

ENTRYPOINT ["/producer"]
