// Code generated by MockGen. DO NOT EDIT.
// Source: controller.go

// Package mock_data is a generated GoMock package.
package mock_data

import (
	reflect "reflect"
	configuration "wiki_updates/configuration"
	models "wiki_updates/models"

	gomock "github.com/golang/mock/gomock"
)

// MockDataSource is a mock of DataSource interface.
type MockDataSource struct {
	ctrl     *gomock.Controller
	recorder *MockDataSourceMockRecorder
}

// MockDataSourceMockRecorder is the mock recorder for MockDataSource.
type MockDataSourceMockRecorder struct {
	mock *MockDataSource
}

// NewMockDataSource creates a new mock instance.
func NewMockDataSource(ctrl *gomock.Controller) *MockDataSource {
	mock := &MockDataSource{ctrl: ctrl}
	mock.recorder = &MockDataSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataSource) EXPECT() *MockDataSourceMockRecorder {
	return m.recorder
}

// GetStatistics mocks base method.
func (m *MockDataSource) GetStatistics() (*models.Statistics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatistics")
	ret0, _ := ret[0].(*models.Statistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatistics indicates an expected call of GetStatistics.
func (mr *MockDataSourceMockRecorder) GetStatistics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatistics", reflect.TypeOf((*MockDataSource)(nil).GetStatistics))
}

// Initialize mocks base method.
func (m *MockDataSource) Initialize(arg0 configuration.Config) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Initialize", arg0)
}

// Initialize indicates an expected call of Initialize.
func (mr *MockDataSourceMockRecorder) Initialize(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockDataSource)(nil).Initialize), arg0)
}

// SaveUpdate mocks base method.
func (m *MockDataSource) SaveUpdate(arg0 models.Update) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUpdate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveUpdate indicates an expected call of SaveUpdate.
func (mr *MockDataSourceMockRecorder) SaveUpdate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUpdate", reflect.TypeOf((*MockDataSource)(nil).SaveUpdate), arg0)
}
