// Code generated by MockGen. DO NOT EDIT.
// Source: configuration.go

// Package mock_configuration is a generated GoMock package.
package mock_configuration

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockConfig is a mock of Config interface.
type MockConfig struct {
	ctrl     *gomock.Controller
	recorder *MockConfigMockRecorder
}

// MockConfigMockRecorder is the mock recorder for MockConfig.
type MockConfigMockRecorder struct {
	mock *MockConfig
}

// NewMockConfig creates a new mock instance.
func NewMockConfig(ctrl *gomock.Controller) *MockConfig {
	mock := &MockConfig{ctrl: ctrl}
	mock.recorder = &MockConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfig) EXPECT() *MockConfigMockRecorder {
	return m.recorder
}

// ClusterHosts mocks base method.
func (m *MockConfig) ClusterHosts() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterHosts")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ClusterHosts indicates an expected call of ClusterHosts.
func (mr *MockConfigMockRecorder) ClusterHosts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterHosts", reflect.TypeOf((*MockConfig)(nil).ClusterHosts))
}

// ClusterKeyspace mocks base method.
func (m *MockConfig) ClusterKeyspace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterKeyspace")
	ret0, _ := ret[0].(string)
	return ret0
}

// ClusterKeyspace indicates an expected call of ClusterKeyspace.
func (mr *MockConfigMockRecorder) ClusterKeyspace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterKeyspace", reflect.TypeOf((*MockConfig)(nil).ClusterKeyspace))
}

// DataStorage mocks base method.
func (m *MockConfig) DataStorage() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataStorage")
	ret0, _ := ret[0].(string)
	return ret0
}

// DataStorage indicates an expected call of DataStorage.
func (mr *MockConfigMockRecorder) DataStorage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataStorage", reflect.TypeOf((*MockConfig)(nil).DataStorage))
}

// Debug mocks base method.
func (m *MockConfig) Debug() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Debug")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Debug indicates an expected call of Debug.
func (mr *MockConfigMockRecorder) Debug() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockConfig)(nil).Debug))
}

// ServerPort mocks base method.
func (m *MockConfig) ServerPort() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServerPort")
	ret0, _ := ret[0].(string)
	return ret0
}

// ServerPort indicates an expected call of ServerPort.
func (mr *MockConfigMockRecorder) ServerPort() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServerPort", reflect.TypeOf((*MockConfig)(nil).ServerPort))
}

// UserAgent mocks base method.
func (m *MockConfig) UserAgent() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserAgent")
	ret0, _ := ret[0].(string)
	return ret0
}

// UserAgent indicates an expected call of UserAgent.
func (mr *MockConfigMockRecorder) UserAgent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserAgent", reflect.TypeOf((*MockConfig)(nil).UserAgent))
}

// WikiAPIURL mocks base method.
func (m *MockConfig) WikiAPIURL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WikiAPIURL")
	ret0, _ := ret[0].(string)
	return ret0
}

// WikiAPIURL indicates an expected call of WikiAPIURL.
func (mr *MockConfigMockRecorder) WikiAPIURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WikiAPIURL", reflect.TypeOf((*MockConfig)(nil).WikiAPIURL))
}
